#ifndef _SRENDERER_COMMON_RT_CONFIG_HEADER_
#define _SRENDERER_COMMON_RT_CONFIG_HEADER_

#define PRIMITIVE_TRIANGLE      0
#define PRIMITIVE_SPHERE        1

#define PRIMITIVE_TYPE_COUNT    2

#define CALLABLE_SAMPLING_OFFSET        0
#define CALLABLE_SPHERE_SAMPLING        0
#define CALLABLE_SPHERE_SAMPLING_PDF    1

#define NOT_A_LIGHT 4294967295

const float T_MAX  = 100000;
const int MAX_DEPTH = 3;
#endif